### ISSUE TITLE
寄信寄不出去

### ISSUE THREAD

**Issue by QQay** [2020-DL-Training-Program/General#1]
HI, 助教, 從公司夾帶檔案繳交作業, 不知道為什麼信件都寄不出去, 想請問是否有其他的繳交作業的方法 ? 或是 ... ??? 這裡可以上傳嗎 ? 我有出現像下面這樣的訊息．

傳遞至下列收件者或群組失敗:
zivzhong.cs07g@nctu.edu.tw
收件者的電子郵件提供者拒絕您的郵件，因此您的郵件未傳遞。
下列組織已拒絕您的郵件: ASPMX.L.GOOGLE.COM。

我該怎麼處理比較好呢？

**Comment by zivzone** [comment]
@QQay 你好，有的我們已經收到 Chloe 寄的這個 issue，目前先統一不登記遲交這件事，我們會再跟 Chloe 討論如何繳交已經 lab1 report 繳交 deadline 為何時。
